# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: download_request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64ownload_request.proto\"B\n\x0f\x44ownloadRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04hour\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x61ta_format\x18\x03 \x01(\t\"<\n\x10\x44ownloadResponse\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x15\n\rfile_contents\x18\x02 \x01(\x0c\x32H\n\x0b\x46ileService\x12\x39\n\x0eGetFolderFiles\x12\x10.DownloadRequest\x1a\x11.DownloadResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'download_request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOWNLOADREQUEST._serialized_start=26
  _DOWNLOADREQUEST._serialized_end=92
  _DOWNLOADRESPONSE._serialized_start=94
  _DOWNLOADRESPONSE._serialized_end=154
  _FILESERVICE._serialized_start=156
  _FILESERVICE._serialized_end=228
# @@protoc_insertion_point(module_scope)
