version: '3'
x-airflow-common:
  &airflow-common
  image: jaihind213/airflow:1.0 
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@${HOST_IP}:5432/postgres
    - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
  volumes:
    - ./dags:/opt/airflow/dags
    - ./airflow-data/logs:/opt/airflow/logs
    - ./airflow-data/plugins:/opt/airflow/plugins
    - ./airflow-data/airflow.cfg:/opt/airlfow/airflow.cfg
    - /tmp/staging:/tmp/staging
    - /tmp/trips_bucket:/tmp/trips_bucket
    - ./config.ini:/tmp/config.ini
  depends_on:
    - postgis

services:
  summary:
    image: jaihind213/summary-api:1.0
    container_name: summary
    ports:
      - 8000:8000
    volumes:
      - ./config2.ini:/app/conf/config.ini 
  influx:
    container_name: influx
    image: influxdb:1.0
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=posgres
      - DOCKER_INFLUXDB_INIT_PASSWORD=postgres
      - DOCKER_INFLUXDB_INIT_ORG=trips
      - DOCKER_INFLUXDB_INIT_BUCKET=trips
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT+8
      - PGTZ=GMT+8
    ports:
      - 5432:5432
    restart: always
  grpc:
    image: jaihind213/data_download_grpc:1.0
    container_name: grpc
    volumes:
      - /tmp/trips_bucket:/app/lake
    ports:
      - 50051:50051
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    ports:
      - "5433:5432"

  airflow-init:
    << : *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - airflow db init &&
        airflow users create
          --role Admin
          --username airflow
          --password airflow
          --email airflow@airflow.com
          --firstname airflow
          --lastname airflow
    restart: on-failure

  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    ports:
      - 8080:8080
    container_name: airflow_webserver
    restart: always

  airflow-scheduler:
    << : *airflow-common
    command: airflow scheduler
    container_name: airflow_scheduler
    restart: always
